# Builder image
FROM registry.access.redhat.com/ubi9/nodejs-20:latest as builder

USER 1001
COPY --chown=1001 components/trustify-ui .
COPY --chown=1001 branding/ui /tmp/rh-branding
RUN npm install -g npm@9
RUN npm clean-install --ignore-scripts && BRANDING=/tmp/rh-branding npm run build && npm run dist

# Runner image
FROM registry.access.redhat.com/ubi9/nodejs-20-minimal:latest

# Add ps package to allow liveness probe for k8s cluster
# Add tar package to allow copying files with kubectl scp
USER 0
RUN microdnf -y install tar procps-ng && microdnf clean all

USER 1001

LABEL name="rhtpa/rhtpa-ui" \
    description="RHTPA - User Interface" \
    help="For more information visit https://developers.redhat.com/products/trusted-profile-analyzer" \
    license="Apache License 2.0" \
    maintainer="rhtpa@redhat.com" \
    summary="RHTPA - User Interface" \
    url="https://developers.redhat.com/products/trusted-profile-analyzer" \
    usage="podman run -p 80 -v rhtpa/rhtpa-ui:latest" \
    io.k8s.display-name="rhtpa-ui" \
    io.k8s.description="RHTPA - User Interface" \
    io.openshift.expose-services="80:http" \
    io.openshift.tags="operator,rhtpa,ui,nodejs20" \
    io.openshift.min-cpu="100m" \
    io.openshift.min-memory="350Mi"

COPY --from=builder /opt/app-root/src/dist /opt/app-root/dist/

ENV DEBUG=1

WORKDIR /opt/app-root/dist
ENTRYPOINT ["./entrypoint.sh"]
